name: Release WoW Addon

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create zip
        run: |
          mkdir build
          rsync -av \
            --exclude '.git' \
            --exclude '.github' \
            --exclude 'build' \
          ./ PetCall/
          zip -r build/PetCall.zip PetCall

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/PetCall.zip
          generate_release_notes: true
